/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import demo.DemoModeImageData;
import java.awt.Dialog;
import java.util.prefs.Preferences;
import org.micromanager.MMStudio;

/**
 *
 * @author Henry
 */
public class SettingsDialog extends javax.swing.JDialog {
   
   Preferences prefs_;
   private GUI gui_;
   private static boolean demoMode_ = false;
   private static boolean afBetweenAcqs_ = false;
   
   
   public SettingsDialog(Preferences prefs, GUI gui) {
      super(gui.getOwner(),Dialog.ModalityType.APPLICATION_MODAL);
      this.setLocationRelativeTo(null);
      prefs_ = prefs;
      gui_ = gui;
      initComponents();
      
          //Demo mode 
      try {
         String s = MMStudio.getInstance().getSysConfigFile();
         if (s.endsWith("NavDemo.cfg") ||s.endsWith("NavDemo16Bit.cfg") ) {
            SettingsDialog.setDemoMode(true);
         } else if (s.contains("BIDC")) {
            //secret features!           
         
         } else {
            //no secret features :(
           autofocusBetweenSerialAcqsCheckBox_.setVisible(false);
         }
      } catch (Exception e) {
      }
   }
   
   
   public static boolean getAutofocusBetweenSerialAcqusitions() {
      return afBetweenAcqs_;
   }
   
   public static boolean getDemoMode() {
      return demoMode_;
   }
   
   public static int getDemoNumChannels() {
      return 6;
   }
   
   public static void setDemoMode(boolean demo) {
      demoMode_ = true;
      new DemoModeImageData();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowSizeButtonGroup_ = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        autofocusBetweenSerialAcqsCheckBox_ = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Micro-Magellan settings");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        autofocusBetweenSerialAcqsCheckBox_.setText("autofocus between serial acqusitions");
        autofocusBetweenSerialAcqsCheckBox_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autofocusBetweenSerialAcqsCheckBox_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(381, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(autofocusBetweenSerialAcqsCheckBox_)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(autofocusBetweenSerialAcqsCheckBox_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
   }//GEN-LAST:event_jButton2ActionPerformed

   private void autofocusBetweenSerialAcqsCheckBox_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autofocusBetweenSerialAcqsCheckBox_ActionPerformed
      afBetweenAcqs_ = autofocusBetweenSerialAcqsCheckBox_.isSelected();
   }//GEN-LAST:event_autofocusBetweenSerialAcqsCheckBox_ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autofocusBetweenSerialAcqsCheckBox_;
    private javax.swing.JButton jButton2;
    private javax.swing.ButtonGroup windowSizeButtonGroup_;
    // End of variables declaration//GEN-END:variables
}
