/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import demo.DemoModeImageData;
import java.awt.Dialog;
import java.util.prefs.Preferences;
import org.micromanager.MMStudio;

/**
 *
 * @author Henry
 */
public class SettingsDialog extends javax.swing.JDialog {
   
   Preferences prefs_;
   private GUI gui_;
   private static int overlapX_ = 0;
   private static int overlapY_ = 0;
   private static boolean demoMode_ = false;
   private static boolean afBetweenAcqs_ = false;
   
   
   public SettingsDialog(Preferences prefs, GUI gui) {
      super(gui.getOwner(),Dialog.ModalityType.APPLICATION_MODAL);
      this.setLocationRelativeTo(null);
      prefs_ = prefs;
      gui_ = gui;
      initComponents();
      
          //Demo mode 
      try {
         String s = MMStudio.getInstance().getSysConfigFile();
         if (s.endsWith("NavDemo.cfg") ||s.endsWith("NavDemo16Bit.cfg") ) {
            SettingsDialog.setDemoMode(true);
         } else if (s.startsWith("BIDC")) {
            //secret features!           
         
         } else {
            //no secret features :(
           autofocusBetweenSerialAcqsCheckBox_.setVisible(false);
         }
      } catch (Exception e) {
      }
   }
   
   
   public static boolean getAutofocusBetweenSerialAcqusitions() {
      return afBetweenAcqs_;
   }
   

   public static int getOverlapX() {
      return overlapX_;
   }
   
   public static int getOverlapY() {
      return overlapY_;
   }
   
   public static boolean getDemoMode() {
      return demoMode_;
   }
   
   public static int getDemoNumChannels() {
      return 6;
   }
   
   public static void setDemoMode(boolean demo) {
      demoMode_ = true;
      new DemoModeImageData();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowSizeButtonGroup_ = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        xOverlapSpinner_ = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        yOverlapSpinner_ = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        autofocusBetweenSerialAcqsCheckBox_ = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Micro-Magellan settings");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jLabel1.setText("Tile pixel overlap x: ");

        xOverlapSpinner_.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        xOverlapSpinner_.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xOverlapSpinner_StateChanged(evt);
            }
        });

        jLabel2.setText("y:");

        yOverlapSpinner_.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        yOverlapSpinner_.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yOverlapSpinner_StateChanged(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        autofocusBetweenSerialAcqsCheckBox_.setText("autofocus between serial acqusitions");
        autofocusBetweenSerialAcqsCheckBox_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autofocusBetweenSerialAcqsCheckBox_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(autofocusBetweenSerialAcqsCheckBox_))
                        .addGap(0, 210, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(yOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(autofocusBetweenSerialAcqsCheckBox_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void xOverlapSpinner_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xOverlapSpinner_StateChanged
      overlapX_ = (Integer) xOverlapSpinner_.getValue();
   }//GEN-LAST:event_xOverlapSpinner_StateChanged

   private void yOverlapSpinner_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yOverlapSpinner_StateChanged
      overlapY_ = (Integer) yOverlapSpinner_.getValue();
   }//GEN-LAST:event_yOverlapSpinner_StateChanged

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
   }//GEN-LAST:event_jButton2ActionPerformed

   private void autofocusBetweenSerialAcqsCheckBox_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autofocusBetweenSerialAcqsCheckBox_ActionPerformed
      afBetweenAcqs_ = autofocusBetweenSerialAcqsCheckBox_.isSelected();
   }//GEN-LAST:event_autofocusBetweenSerialAcqsCheckBox_ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autofocusBetweenSerialAcqsCheckBox_;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.ButtonGroup windowSizeButtonGroup_;
    private javax.swing.JSpinner xOverlapSpinner_;
    private javax.swing.JSpinner yOverlapSpinner_;
    // End of variables declaration//GEN-END:variables
}
