/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportProblemDialog.java
 *
 * Created on Feb 3, 2011, 11:49:27 AM
 */
package org.micromanager;

import java.util.logging.Level;
import java.util.logging.Logger;
import mmcorej.CMMCore;
import org.micromanager.api.DeviceControlGUI;
import org.micromanager.utils.ReportingUtils;

/**
 *
 * @author karlhoover
 */
public class ReportProblemDialog extends javax.swing.JDialog {

    private Integer step_;
    String reportPreamble_;
    CMMCore core_;
    private DeviceControlGUI parent_;
    String configPath_;

    /** Creates new form ReportProblemDialog */
    public ReportProblemDialog(CMMCore c, DeviceControlGUI parentMMGUI, String configPath) {
        super();
        //(parent, modal);
        initComponents();
        reportPreamble_ = "";
        step_ = 0;
        core_ = c;
        parent_ = parentMMGUI;
        configPath_ = configPath;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SkipButton_ = new javax.swing.JButton();
        NextButton_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StepInstructions_ = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescriptionPane_ = new javax.swing.JEditorPane();
        CancelButton_ = new javax.swing.JButton();
        DoneButton_ = new javax.swing.JButton();

        setTitle("Report Problem Dialog");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        SkipButton_.setText("Skip");
        SkipButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipButton_ActionPerformed(evt);
            }
        });

        NextButton_.setText("Next");
        NextButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton_ActionPerformed(evt);
            }
        });

        StepInstructions_.setColumns(20);
        StepInstructions_.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10));
        StepInstructions_.setLineWrap(true);
        StepInstructions_.setRows(5);
        StepInstructions_.setWrapStyleWord(true);
        jScrollPane1.setViewportView(StepInstructions_);

        DescriptionPane_.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10));
        jScrollPane2.setViewportView(DescriptionPane_);

        CancelButton_.setText("Cancel");
        CancelButton_.setToolTipText("Quit the Problem Report procedure.");
        CancelButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton_ActionPerformed(evt);
            }
        });

        DoneButton_.setText("Done");
        DoneButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton_ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, DoneButton_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, NextButton_, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, SkipButton_, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(249, 249, 249)
                        .add(CancelButton_)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(SkipButton_)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(NextButton_))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CancelButton_))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(DoneButton_)
                        .add(8, 8, 8))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SkipButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipButton_ActionPerformed
        switch (step_) {
            case 0:
                break;
            case 1:
                step_ = step_ + 1;
                NextButton_.setText("Next");
                SkipButton_.setVisible(false);
                break;
            case 2:
                BuildAndSendReport();
                break;
            default:
                break;

        }
    }//GEN-LAST:event_SkipButton_ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        SkipButton_.setVisible(false);
        InitializeDialog();

    }//GEN-LAST:event_formComponentShown

    private void NextButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton_ActionPerformed
        switch (step_) {
            case 0:
                SkipButton_.setVisible(true);
                NextButton_.setText("Clear!");
                StepInstructions_.setText("If the system has been running for some time, the log file is likely very large,"
                        + " and may take a long time to send. If you can easily replicate the problem situation, press Clear!"
                        + " to restart the log file anew. Else press skip to leave your log file intact.");
                step_ = 1;
                break;
            case 1:
                // user wishes to clear the log file..
                core_.clearLog();
                core_.logMessage("MM Studio version: " + parent_.getVersion());
                core_.logMessage(core_.getVersionInfo());
                core_.logMessage(core_.getAPIVersionInfo());
                core_.logMessage("Operating System: " + System.getProperty("os.name") + " " + System.getProperty("os.version"));
                NextButton_.setText("Next");
                StepInstructions_.setText("Now operate the system until you've duplicated the problem. When you're successful, "
                        +"press Next to send your problem description, system configuration, and log to micro-manager.org.");
                step_ = 2;
                break;
            case 2:
                BuildAndSendReport();
                break;
            case 3:
                InitializeDialog();
                setVisible(false);
                break;
            default:

                break;
        }
    }//GEN-LAST:event_NextButton_ActionPerformed

    private void BuildAndSendReport() {
        reportPreamble_ = "#User Description: " + DescriptionPane_.getText();
        DescriptionPane_.setEnabled(false);
        DescriptionPane_.setEditable(false);
        StepInstructions_.setText("Sending...");
        ProblemReportSender p = new ProblemReportSender(reportPreamble_, core_, configPath_);
        String result = p.Send();
        if (0 < result.length()) {
            ReportingUtils.logError(result);
            StepInstructions_.setText("There was a problem sending the report, please verify your internet connection.");
        } else {
            StepInstructions_.setText("The report was successfully submitted to micro-manager.org");
        }
        step_ = 3;
        SkipButton_.setVisible(false);
    }

    private void CancelButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton_ActionPerformed
        InitializeDialog();
        this.setVisible(false);
    }//GEN-LAST:event_CancelButton_ActionPerformed

    private void DoneButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton_ActionPerformed
        InitializeDialog();
        this.setVisible(false);
    }//GEN-LAST:event_DoneButton_ActionPerformed

    void InitializeDialog() {
        step_ = 0;
        StepInstructions_.setText("Please describe the problem in the panel below:");
        DescriptionPane_.setText("");
        DescriptionPane_.setVisible(true);
        DescriptionPane_.setEditable(true);
        DescriptionPane_.setEnabled(true);
        DescriptionPane_.requestFocus();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton_;
    private javax.swing.JEditorPane DescriptionPane_;
    private javax.swing.JButton DoneButton_;
    private javax.swing.JButton NextButton_;
    private javax.swing.JButton SkipButton_;
    private javax.swing.JTextArea StepInstructions_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
