package gui;


import acq.CustomAcqEngine;
import com.sun.imageio.plugins.common.ImageUtil;
import ij.gui.ImageWindow;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.prefs.Preferences;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import org.jdesktop.swingx.*;
import org.jdesktop.swingx.multislider.DefaultMultiThumbModel;
import org.jdesktop.swingx.multislider.MultiThumbModel;
import org.micromanager.MMStudio;
import org.micromanager.imagedisplay.VirtualAcquisitionDisplay;
import org.micromanager.utils.GUIUtils;
import org.micromanager.utils.ImageFocusListener;


/**
 *
 * @author Henry
 */
public class GUI extends javax.swing.JFrame implements ImageFocusListener {

   
   private CustomAcqEngine eng_;
   private DisplayPlus currentDisplay_;
   private Preferences prefs_;
           
           
   public GUI(Preferences prefs) {
      prefs_ = prefs;
      initComponents();
      this.setVisible(true);
      eng_ = new CustomAcqEngine(MMStudio.getInstance().getCore());
      GUIUtils.registerImageFocusListener(this);
   }
     
   @Override
   public void focusReceived(ImageWindow focusedWindow) {
       if (focusedWindow == null) {
           currentDisplay_ = null;
           return;
       }
      Object disp = VirtualAcquisitionDisplay.getDisplay(focusedWindow.getImagePlus());
      if (disp == null || !(disp instanceof DisplayPlus) ) {
         currentDisplay_ = null;
      } else {
         currentDisplay_ = (DisplayPlus) disp;
      }
      //TODO enable GUI controls specific to window type
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zSliderPanel_ = new javax.swing.JPanel();
        zTextField_ = new javax.swing.JTextField();
        zSlider_ = new javax.swing.JSlider();
        propertiesPanel_ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exploreControlsPanel_ = new javax.swing.JPanel();
        newExploreWindowButton_ = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        windowControlsPanel = new javax.swing.JPanel();
        fullResButton_ = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        zTextField_.setText("jTextField1");

        javax.swing.GroupLayout zSliderPanel_Layout = new javax.swing.GroupLayout(zSliderPanel_);
        zSliderPanel_.setLayout(zSliderPanel_Layout);
        zSliderPanel_Layout.setHorizontalGroup(
            zSliderPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zSliderPanel_Layout.createSequentialGroup()
                .addComponent(zTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zSlider_, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zSliderPanel_Layout.setVerticalGroup(
            zSliderPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zSlider_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(zTextField_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("add focus changable props here");

        javax.swing.GroupLayout propertiesPanel_Layout = new javax.swing.GroupLayout(propertiesPanel_);
        propertiesPanel_.setLayout(propertiesPanel_Layout);
        propertiesPanel_Layout.setHorizontalGroup(
            propertiesPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(propertiesPanel_Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        propertiesPanel_Layout.setVerticalGroup(
            propertiesPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanel_Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        newExploreWindowButton_.setText("New explore window");
        newExploreWindowButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newExploreWindowButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exploreControlsPanel_Layout = new javax.swing.GroupLayout(exploreControlsPanel_);
        exploreControlsPanel_.setLayout(exploreControlsPanel_Layout);
        exploreControlsPanel_Layout.setHorizontalGroup(
            exploreControlsPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(exploreControlsPanel_Layout.createSequentialGroup()
                .addComponent(newExploreWindowButton_)
                .addContainerGap())
        );
        exploreControlsPanel_Layout.setVerticalGroup(
            exploreControlsPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exploreControlsPanel_Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newExploreWindowButton_)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        fullResButton_.setText("Full resolution");
        fullResButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullResButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout windowControlsPanelLayout = new javax.swing.GroupLayout(windowControlsPanel);
        windowControlsPanel.setLayout(windowControlsPanelLayout);
        windowControlsPanelLayout.setHorizontalGroup(
            windowControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(windowControlsPanelLayout.createSequentialGroup()
                .addComponent(fullResButton_)
                .addContainerGap())
        );
        windowControlsPanelLayout.setVerticalGroup(
            windowControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowControlsPanelLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(fullResButton_))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertiesPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(windowControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zSliderPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(exploreControlsPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zSliderPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(propertiesPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exploreControlsPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void newExploreWindowButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newExploreWindowButton_ActionPerformed
      new ExploreInitDialog(prefs_, eng_);
   }//GEN-LAST:event_newExploreWindowButton_ActionPerformed

   private void fullResButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullResButton_ActionPerformed

   }//GEN-LAST:event_fullResButton_ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exploreControlsPanel_;
    private javax.swing.JButton fullResButton_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton newExploreWindowButton_;
    private javax.swing.JPanel propertiesPanel_;
    private javax.swing.JPanel windowControlsPanel;
    private javax.swing.JPanel zSliderPanel_;
    private javax.swing.JSlider zSlider_;
    private javax.swing.JTextField zTextField_;
    // End of variables declaration//GEN-END:variables


}
