/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import demo.DemoModeImageData;
import java.awt.Dialog;
import java.util.prefs.Preferences;

/**
 *
 * @author Henry
 */
public class SettingsDialog extends javax.swing.JDialog {

   private static final String PREF_AUTO_IMAGE_SIZE = "Auto image size";
   private static final String PREF_WIDTH = "Image width";
   private static final String PREF_HEIGHT = "Image height";
   
   
   Preferences prefs_;
   private GUI gui_;
   private static int overlapX_ = 0;
   private static int overlapY_ = 0;
   private static boolean demoMode_ = false;
   private static boolean autoImageSize_;
   private static int imageWidth_, imageHeight_;
   
   
   public SettingsDialog(Preferences prefs, GUI gui) {
      super(gui.getOwner(),Dialog.ModalityType.APPLICATION_MODAL);
      this.setLocationRelativeTo(null);
      prefs_ = prefs;
      gui_ = gui;
      initComponents();
      loadPrefs();
   }
   
   private void loadPrefs() {
      imageHeightSpinner_.setValue(prefs_.getInt(PREF_HEIGHT, 512));
      imageWidthSpinner_.setValue(prefs_.getInt(PREF_WIDTH, 512));
      imageHeight_ = prefs_.getInt(PREF_HEIGHT, 512);
      imageWidth_ = prefs_.getInt(PREF_WIDTH, 512);
      autoButton_.setSelected(prefs_.getBoolean(PREF_AUTO_IMAGE_SIZE, true));
      autoImageSize_ = prefs_.getBoolean(PREF_AUTO_IMAGE_SIZE, true);     
   }
   
   private void savePrefs() {
      prefs_.putBoolean(PREF_AUTO_IMAGE_SIZE, autoButton_.isSelected());
      prefs_.putInt(PREF_WIDTH, (Integer) imageWidthSpinner_.getValue());
      prefs_.putInt(PREF_HEIGHT, (Integer) imageHeightSpinner_.getValue());
   }
   
   public static boolean getAutoImageSize() {
      return autoImageSize_;
   }

   public static int getImageWidth() {
      return imageWidth_;
   }
   
   public static int getImageHeight() {
      return imageHeight_;
   }
   
   public static int getOverlapX() {
      return overlapX_;
   }
   
   public static int getOverlapY() {
      return overlapY_;
   }
   
   public static boolean getDemoMode() {
      return demoMode_;
   }
   
   public static int getDemoNumChannels() {
      return 6;
   }
   
   public static void setDemoMode(boolean demo) {
      demoMode_ = true;
      new DemoModeImageData();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowSizeButtonGroup_ = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        xOverlapSpinner_ = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        yOverlapSpinner_ = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        autoButton_ = new javax.swing.JRadioButton();
        customButton_ = new javax.swing.JRadioButton();
        imageWidthSpinner_ = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        imageHeightSpinner_ = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("5D Navigator settings");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jLabel1.setText("Tile pixel overlap x: ");

        xOverlapSpinner_.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        xOverlapSpinner_.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xOverlapSpinner_StateChanged(evt);
            }
        });

        jLabel2.setText("y:");

        yOverlapSpinner_.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        yOverlapSpinner_.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yOverlapSpinner_StateChanged(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Image window size: ");

        windowSizeButtonGroup_.add(autoButton_);
        autoButton_.setText("Auto");
        autoButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoButton_ActionPerformed(evt);
            }
        });

        windowSizeButtonGroup_.add(customButton_);
        customButton_.setText("Custom:");
        customButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton_ActionPerformed(evt);
            }
        });

        imageWidthSpinner_.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(512), Integer.valueOf(2), null, Integer.valueOf(1)));
        imageWidthSpinner_.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                imageWidthSpinner_StateChanged(evt);
            }
        });

        jLabel4.setText("by");

        imageHeightSpinner_.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(512), Integer.valueOf(2), null, Integer.valueOf(1)));
        imageHeightSpinner_.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                imageHeightSpinner_StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autoButton_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customButton_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageWidthSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageHeightSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(yOverlapSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(autoButton_)
                    .addComponent(customButton_)
                    .addComponent(imageWidthSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(imageHeightSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void xOverlapSpinner_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xOverlapSpinner_StateChanged
      overlapX_ = (Integer) xOverlapSpinner_.getValue();
   }//GEN-LAST:event_xOverlapSpinner_StateChanged

   private void yOverlapSpinner_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yOverlapSpinner_StateChanged
      overlapY_ = (Integer) yOverlapSpinner_.getValue();
   }//GEN-LAST:event_yOverlapSpinner_StateChanged

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
   }//GEN-LAST:event_jButton2ActionPerformed

   private void customButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton_ActionPerformed
      autoImageSize_ = !customButton_.isSelected();
      savePrefs();
   }//GEN-LAST:event_customButton_ActionPerformed

   private void autoButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoButton_ActionPerformed
     autoImageSize_ = autoButton_.isSelected();
     savePrefs();
   }//GEN-LAST:event_autoButton_ActionPerformed

   private void imageHeightSpinner_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_imageHeightSpinner_StateChanged
      imageHeight_ = (Integer) imageHeightSpinner_.getValue();
      savePrefs();
   }//GEN-LAST:event_imageHeightSpinner_StateChanged

   private void imageWidthSpinner_StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_imageWidthSpinner_StateChanged
      imageWidth_ = (Integer) imageWidthSpinner_.getValue();
      savePrefs();
   }//GEN-LAST:event_imageWidthSpinner_StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autoButton_;
    private javax.swing.JRadioButton customButton_;
    private javax.swing.JSpinner imageHeightSpinner_;
    private javax.swing.JSpinner imageWidthSpinner_;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup windowSizeButtonGroup_;
    private javax.swing.JSpinner xOverlapSpinner_;
    private javax.swing.JSpinner yOverlapSpinner_;
    // End of variables declaration//GEN-END:variables
}
