
import org.micromanager.MMStudioMainFrame;


/**
 *
 * @author Henry
 */
public class GUI extends javax.swing.JFrame {

   
   private CustomAcqEngine eng_;
   private DisplayPlus currentDisplay_;
           
           
   public GUI() {
      initComponents();
      this.setVisible(true);
      eng_ = new CustomAcqEngine(MMStudioMainFrame.getInstance().getCore());
      
   }
   
   private void newExplorerWindow() {
      eng_.newExploreWindow();
   }
   

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zSliderPanel_ = new javax.swing.JPanel();
        zTextField_ = new javax.swing.JTextField();
        zSlider_ = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        propertiesPanel_ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        exploreControlsPanel_ = new javax.swing.JPanel();
        newExploreWindowButton_ = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        windowControlsPanel = new javax.swing.JPanel();
        numRowsSpinner_ = new javax.swing.JSpinner();
        newGridButton_ = new javax.swing.JButton();
        rowsLabel_ = new javax.swing.JLabel();
        colsLabel_ = new javax.swing.JLabel();
        numColsSpinner_ = new javax.swing.JSpinner();
        createGridButton_ = new javax.swing.JButton();
        fullResButton_ = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zTextField_.setText("jTextField1");

        javax.swing.GroupLayout zSliderPanel_Layout = new javax.swing.GroupLayout(zSliderPanel_);
        zSliderPanel_.setLayout(zSliderPanel_Layout);
        zSliderPanel_Layout.setHorizontalGroup(
            zSliderPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zSliderPanel_Layout.createSequentialGroup()
                .addComponent(zTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zSlider_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zSliderPanel_Layout.setVerticalGroup(
            zSliderPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zSlider_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(zTextField_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("add focus changable props here");

        javax.swing.GroupLayout propertiesPanel_Layout = new javax.swing.GroupLayout(propertiesPanel_);
        propertiesPanel_.setLayout(propertiesPanel_Layout);
        propertiesPanel_Layout.setHorizontalGroup(
            propertiesPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanel_Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        propertiesPanel_Layout.setVerticalGroup(
            propertiesPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanel_Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        newExploreWindowButton_.setText("New explore window");
        newExploreWindowButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newExploreWindowButton_ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Expand");

        javax.swing.GroupLayout exploreControlsPanel_Layout = new javax.swing.GroupLayout(exploreControlsPanel_);
        exploreControlsPanel_.setLayout(exploreControlsPanel_Layout);
        exploreControlsPanel_Layout.setHorizontalGroup(
            exploreControlsPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exploreControlsPanel_Layout.createSequentialGroup()
                .addComponent(newExploreWindowButton_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exploreControlsPanel_Layout.setVerticalGroup(
            exploreControlsPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exploreControlsPanel_Layout.createSequentialGroup()
                .addGroup(exploreControlsPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newExploreWindowButton_)
                    .addComponent(jCheckBox1))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        numRowsSpinner_.setEnabled(false);

        newGridButton_.setText("New Grid");
        newGridButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGridButton_ActionPerformed(evt);
            }
        });

        rowsLabel_.setText("Rows");
        rowsLabel_.setEnabled(false);

        colsLabel_.setText("Columns");
        colsLabel_.setEnabled(false);

        numColsSpinner_.setEnabled(false);

        createGridButton_.setText("Create");
        createGridButton_.setEnabled(false);

        fullResButton_.setText("Full resolution");
        fullResButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullResButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout windowControlsPanelLayout = new javax.swing.GroupLayout(windowControlsPanel);
        windowControlsPanel.setLayout(windowControlsPanelLayout);
        windowControlsPanelLayout.setHorizontalGroup(
            windowControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowControlsPanelLayout.createSequentialGroup()
                .addGroup(windowControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(windowControlsPanelLayout.createSequentialGroup()
                        .addComponent(newGridButton_)
                        .addGap(5, 5, 5)
                        .addComponent(rowsLabel_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numRowsSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colsLabel_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numColsSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createGridButton_))
                    .addComponent(fullResButton_))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        windowControlsPanelLayout.setVerticalGroup(
            windowControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowControlsPanelLayout.createSequentialGroup()
                .addGroup(windowControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numRowsSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGridButton_)
                    .addComponent(rowsLabel_)
                    .addComponent(colsLabel_)
                    .addComponent(numColsSpinner_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createGridButton_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fullResButton_))
        );

        jLabel2.setText("add acquisition controls");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zSliderPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(propertiesPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(exploreControlsPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(windowControlsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zSliderPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertiesPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exploreControlsPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void newExploreWindowButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newExploreWindowButton_ActionPerformed
      newExplorerWindow();
   }//GEN-LAST:event_newExploreWindowButton_ActionPerformed

   private void fullResButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullResButton_ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_fullResButton_ActionPerformed

   private void newGridButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGridButton_ActionPerformed
      boolean selected = newGridButton_.isSelected();
      //clear other buttons as appropriate
      newGridButton_.setText(selected ? "Cancel" : "New Grid");      
      numColsSpinner_.setEnabled(selected);
      numRowsSpinner_.setEnabled(selected);
      rowsLabel_.setEnabled(selected);
      colsLabel_.setEnabled(selected);
      createGridButton_.setEnabled(selected);
   }//GEN-LAST:event_newGridButton_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colsLabel_;
    private javax.swing.JButton createGridButton_;
    private javax.swing.JPanel exploreControlsPanel_;
    private javax.swing.JButton fullResButton_;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton newExploreWindowButton_;
    private javax.swing.JButton newGridButton_;
    private javax.swing.JSpinner numColsSpinner_;
    private javax.swing.JSpinner numRowsSpinner_;
    private javax.swing.JPanel propertiesPanel_;
    private javax.swing.JLabel rowsLabel_;
    private javax.swing.JPanel windowControlsPanel;
    private javax.swing.JPanel zSliderPanel_;
    private javax.swing.JSlider zSlider_;
    private javax.swing.JTextField zTextField_;
    // End of variables declaration//GEN-END:variables
}
