///////////////////////////////////////////////////////////////////////////////
//PROJECT:       Micro-Manager
//-----------------------------------------------------------------------------
//
// AUTHOR:       Chris Weisiger, 2015
//
// COPYRIGHT:    University of California, San Francisco, 2015
//
// LICENSE:      This file is distributed under the BSD license.
//               License text is included with the source distribution.
//
//               This file is distributed in the hope that it will be useful,
//               but WITHOUT ANY WARRANTY; without even the implied warranty
//               of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//
//               IN NO EVENT SHALL THE COPYRIGHT OWNER OR
//               CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
//               INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES.

package org.micromanager.quickaccess;

import java.awt.Window;

import javax.swing.JComponent;

import org.micromanager.PropertyMap;

/**
 * This plugin allows arbitrary controls ("widgets") to be included in the
 * Quick-Access Window. It gives you the maximum control over how your control
 * will appear and behave. However, it also requires you to implement the most
 * logic.
 */
public interface WidgetPlugin extends QuickAccessPlugin {
   /**
    * Create the GUI components for this control.
    * @param config A PropertyMap as output by configureControl used to
    *        configure this control. The PropertyMap may be empty.
    */
   public JComponent createControl(PropertyMap config);

   /**
    * Generate configuration information that can be used to configure a
    * control generated by this plugin. This method will only ever be called in
    * a new thread; it is allowed to block indefinitely (e.g. to show modal
    * dialogs to the user); however the control will not be usable until
    * configuration is completed.
    * @param parent The Quick-Access Window
    */
   public PropertyMap configureControl(Window parent);
}
