/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChannelControlsPanel.java
 *
 * Created on Sep 27, 2010, 1:27:24 PM
 */
package org.micromanager.acquisition;

import ij.ImagePlus;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import javax.swing.BoxLayout;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SpringLayout;
import javax.swing.SwingUtilities;
import org.micromanager.graph.GraphData;
import org.micromanager.graph.HistogramPanel;
import org.micromanager.graph.HistogramPanel.CursorListener;
import org.micromanager.utils.HistogramUtils;
import org.micromanager.utils.MDUtils;
import org.micromanager.utils.MMScriptException;
import org.micromanager.utils.MathFunctions;
import org.micromanager.utils.ReportingUtils;

/**
 *
 * @author arthur
 */
public class ChannelControlPanel extends javax.swing.JPanel {

   private final int channelIndex_;
   private final VirtualAcquisitionDisplay acq_;
   private final HistogramPanel hp_;
   private final MetadataPanel metadataPanel_;

   private double binSize_;
   private boolean autostretch_ = false;
   private boolean rejectOutliers_ = false;
   private boolean logScale_ = false;
   private double fractionToReject_;
   private int height_;
   private String histMax_;

   /** Creates new form ChannelControlsPanel */
   public ChannelControlPanel(VirtualAcquisitionDisplay acq, int channelIndex,
           MetadataPanel metadataPanel, int height) {
      height_ = height;
      initComponents(); 
      channelIndex_ = channelIndex;
      acq_ = acq;
      hp_ = addHistogramPanel();
      metadataPanel_ = metadataPanel;
      HistogramUtils huu = new HistogramUtils(null);
      fractionToReject_ = huu.getFractionToReject();
      updateChannelSettings();

   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      fullButton = new javax.swing.JButton();
      autoButton = new javax.swing.JButton();
      colorPickerLabel = new javax.swing.JLabel();
      channelNameCheckbox = new javax.swing.JCheckBox();
      histogramPanelHolder = new javax.swing.JPanel();
      zoomInButton = new javax.swing.JButton();
      zoomOutButton = new javax.swing.JButton();
      minLabel = new javax.swing.JLabel();
      maxLabel = new javax.swing.JLabel();

      setOpaque(false);
      setPreferredSize(new java.awt.Dimension(250,height_ ));

      fullButton.setFont(fullButton.getFont().deriveFont((float)9));
      fullButton.setText("Full");
      fullButton.setToolTipText("Stretch the display gamma curve over the full pixel range");
      fullButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
      fullButton.setPreferredSize(new java.awt.Dimension(75, 30));
      fullButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            fullButtonActionPerformed(evt);
         }
      });

      autoButton.setFont(autoButton.getFont().deriveFont((float)9));
      autoButton.setText("Auto");
      autoButton.setToolTipText("Align the display gamma curve with minimum and maximum measured intensity values");
      autoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      autoButton.setIconTextGap(0);
      autoButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
      autoButton.setMaximumSize(new java.awt.Dimension(75, 30));
      autoButton.setMinimumSize(new java.awt.Dimension(75, 30));
      autoButton.setPreferredSize(new java.awt.Dimension(75, 30));
      autoButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            autoButtonActionPerformed(evt);
         }
      });

      colorPickerLabel.setBackground(new java.awt.Color(255, 102, 51));
      colorPickerLabel.setToolTipText("Change the color for displaying this channel");
      colorPickerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      colorPickerLabel.setOpaque(true);
      colorPickerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            colorPickerLabelMouseClicked(evt);
         }
      });

      channelNameCheckbox.setSelected(true);
      channelNameCheckbox.setText("Channel");
      channelNameCheckbox.setToolTipText("Show/hide this channel in the multi-dimensional viewer");
      channelNameCheckbox.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            channelNameCheckboxActionPerformed(evt);
         }
      });

      histogramPanelHolder.setToolTipText("Adjust the brightness and contrast by dragging triangles at top and bottom. Change the gamma by dragging the curve. (These controls only change display, and do not edit the image data.)");
      histogramPanelHolder.setAlignmentX(0.3F);
      histogramPanelHolder.setPreferredSize(new java.awt.Dimension(0, 100));
      histogramPanelHolder.setLayout(new BorderLayout());
      
      zoomInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/micromanager/icons/zoom_in.png"))); // NOI18N
      zoomInButton.setToolTipText("Histogram zoom in");
      zoomInButton.setMaximumSize(new java.awt.Dimension(20, 20));
      zoomInButton.setMinimumSize(new java.awt.Dimension(20, 20));
      zoomInButton.setPreferredSize(new java.awt.Dimension(20, 20));
      zoomInButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            zoomInButtonActionPerformed(evt);
         }
      });

      zoomOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/micromanager/icons/zoom_out.png"))); // NOI18N
      zoomOutButton.setToolTipText("Histogram zoom out");
      zoomOutButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            zoomOutButtonActionPerformed(evt);
         }
      });

      minLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
      minLabel.setText("min");

      maxLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
      maxLabel.setText("max");

      histMax_ = "   ";

      
      this.setLayout(new BorderLayout());
      JPanel controlHolder = new JPanel();
      JPanel controls = new JPanel();
      this.add(controlHolder,BorderLayout.LINE_START);
      controlHolder.add(controls);
      GridBagLayout gbl = new GridBagLayout();
      controls.setLayout(gbl);

      controls.setMaximumSize(new Dimension(160,height_));
      
      this.add(histogramPanelHolder,BorderLayout.CENTER);
      
      
      GridBagConstraints gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 0;
      gbc.gridwidth = 7;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.anchor = GridBagConstraints.NORTHWEST;
      controls.add(channelNameCheckbox,gbc);
        
      gbc = new GridBagConstraints();
      gbc.gridx = 1;
      gbc.gridy = 1;
      gbc.ipadx = 15;
      gbc.ipady = 15;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.gridwidth = 3;
      gbc.insets = new Insets(2,2,2,2);
      controls.add(colorPickerLabel,gbc);
      
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 2;
      gbc.gridwidth = 1;
      gbc.weightx = 1;
      gbc.weighty = 1;     
      gbc.insets = new Insets(2,2,2,2);
      gbc.fill = GridBagConstraints.NONE;
      zoomInButton.setPreferredSize(new Dimension(22,22));
      controls.add(zoomInButton,gbc);
      
      gbc = new GridBagConstraints();
      gbc.gridx = 1;
      gbc.gridy = 2;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.gridwidth = 1;
      gbc.insets = new Insets(2,2,2,2);
      gbc.fill = GridBagConstraints.NONE;
      zoomOutButton.setPreferredSize(new Dimension(22,22));
      controls.add(zoomOutButton,gbc);
      
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 3;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.gridwidth = 7;
      gbc.anchor = GridBagConstraints.LINE_START;
      controls.add(minLabel,gbc);
      
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 4;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.gridwidth = 7;
      gbc.anchor = GridBagConstraints.LINE_START;
      controls.add(maxLabel,gbc);
      
      gbc = new GridBagConstraints();
      gbc.gridx = 5;
      gbc.gridy = 1;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.gridwidth = 1;
      fullButton.setPreferredSize(new Dimension(50,20));
      controls.add(fullButton,gbc);
      
      gbc = new GridBagConstraints();
      gbc.gridx = 5;
      gbc.gridy = 2;
      gbc.weightx = 1;
      gbc.weighty = 1;
      gbc.gridwidth = 1;
      autoButton.setPreferredSize(new Dimension(50,20));
      controls.add(autoButton,gbc);


   }
   
   public void setHeight(int height) {    
      hp_.setSize(hp_.getWidth(),height);
      histogramPanelHolder.setSize(hp_.getSize());
      this.setSize(this.getSize().width, height);
   }

    private void fullButtonActionPerformed(java.awt.event.ActionEvent evt) {
       setFullRange();
       acq_.updateAndDraw();
    }

    private void colorPickerLabelMouseClicked(java.awt.event.MouseEvent evt) {
       editColor();
       acq_.updateAndDraw();
    }

    private void channelNameCheckboxActionPerformed(java.awt.event.ActionEvent evt) {
       updateChannelVisibility();
       drawDisplaySettings();
       acq_.updateAndDraw();
    }
    
    public void autoScale() {
       setAutoRange();
       acq_.updateAndDraw();
    }
    
    private void autoButtonActionPerformed(java.awt.event.ActionEvent evt) {
       setAutoRange();
       acq_.updateAndDraw();
    }

    private void zoomInButtonActionPerformed(java.awt.event.ActionEvent evt) {
       binSize_ = Math.max(binSize_ / 2, 1./8);
       drawDisplaySettings();
       updateChannelSettings();
    }

    private void zoomOutButtonActionPerformed(java.awt.event.ActionEvent evt) {
       binSize_ = Math.min(binSize_ * 2, 256);
       drawDisplaySettings();
       updateChannelSettings();
    }

   private javax.swing.JButton autoButton;
   private javax.swing.JCheckBox channelNameCheckbox;
   private javax.swing.JLabel colorPickerLabel;
   private javax.swing.JButton fullButton;
   private javax.swing.JPanel histogramPanelHolder;
   private javax.swing.JLabel maxLabel;
   private javax.swing.JLabel minLabel;
   private javax.swing.JButton zoomInButton;
   private javax.swing.JButton zoomOutButton;

   private void editColor() {
      String name = "selected";
      if (acq_.getChannelNames() != null) {
         name = acq_.getChannelNames()[channelIndex_];
      }
      Color newColor = JColorChooser.showDialog(this, "Choose a color for the "
              + name
              + " channel", acq_.getChannelColor(channelIndex_));

      if (newColor != null && acq_ != null) {
         try {
            acq_.setChannelColor(channelIndex_, newColor.getRGB());
         } catch (MMScriptException ex) {
            ReportingUtils.logError(ex);
         }
      }
      updateChannelSettings();
   }

   public void setAutostretch(boolean state) {
      if (state && !autostretch_) {
         setAutoRange();
      }
      autostretch_ = state;
   }

   public void setRejectOutliers(boolean v){
      rejectOutliers_ = v;
   }

   public void setLogScale(boolean logScale) {
      logScale_ = logScale;
      updateChannelSettings();
   }

   private void updateChannelVisibility() {
      acq_.setChannelVisibility(channelIndex_, channelNameCheckbox.isSelected());
   }

   private void turnOffAutostretch() {
      metadataPanel_.setAutostretch(false);
      autostretch_ = false;
   }

   public final HistogramPanel addHistogramPanel() {
      HistogramPanel hp = new HistogramPanel() {
        @Override
        public void paint(Graphics g) {
           super.paint(g);
          g.setColor(Color.black);
          g.setFont(new Font("Lucida Grande", 0, 10));
          g.drawString(histMax_, this.getSize().width - 36, this.getSize().height );
        }
      };
      hp.setMargins(8, 12);
      hp.setTextVisible(false);
      hp.setGridVisible(false);
      histogramPanelHolder.add(hp, BorderLayout.CENTER);
//      histogramPanelHolder.add(histMaxLabel,BorderLayout.PAGE_END );
      updateBinSize();
      
      hp.addCursorListener(new CursorListener() {
         public void onLeftCursor(double pos) {
            turnOffAutostretch();
            int max = acq_.getChannelMax(channelIndex_);

            int min = (int) (pos * binSize_);
            if (min > max) {
               max = min;
            }
            setDisplayRange(min, max);
            drawDisplaySettings();
            
            acq_.updateAndDraw();
         }

         public void onRightCursor(double pos) {
            turnOffAutostretch();
            int min = acq_.getChannelMin(channelIndex_);

            int max = (int) (pos * binSize_);
            if (max < min) {
               min = max;
            }
            setDisplayRange(min, max);
            drawDisplaySettings();
            acq_.updateAndDraw();
            
         }

         public void onGammaCurve(double gamma) {
            if (gamma == 0)
               return;
            
            if (gamma < 1.15 && gamma > 0.85)
               gamma = 1.0;
            else
               gamma = MathFunctions.clip(0.05, gamma, 20);
            acq_.setChannelGamma(channelIndex_, gamma);
            drawDisplaySettings();
            acq_.updateAndDraw();
         }
      });

      hp.addMouseWheelListener(new MouseWheelListener() {
         public void mouseWheelMoved(MouseWheelEvent e) {
            int notches = e.getWheelRotation();
            binSize_ = Math.min(Math.max(binSize_ * Math.pow(2, 0.5 * notches), 1./8), 256);
            updateChannelSettings();
            drawDisplaySettings();
         }
      });

      return hp;
   }


   public final void updateChannelSettings() {
      if (acq_ != null) {
         Color color = acq_.getChannelColor(channelIndex_);
         colorPickerLabel.setBackground(color);

         String [] names = acq_.getChannelNames();
         if (names != null && channelIndex_ < names.length) {
            channelNameCheckbox.setText(names[channelIndex_]);
         }

         int [] histogram = acq_.getChannelHistogram(channelIndex_);
         hp_.setData(makeGraphData(histogram));
         hp_.setAutoBounds();
         hp_.setTraceStyle(true, color);
        // drawDisplaySettings();
      }
   }

   private int getMaxValue() {
         int type = acq_.getImagePlus().getType();
         int maxValue = 0;
         if (type == ImagePlus.GRAY8)
            maxValue = 1 << 8;
         if (type == ImagePlus.GRAY16) {
            try {
               maxValue = 1 << MDUtils.getBitDepth(acq_.getSummaryMetadata());
            } catch (Exception ex) {
               maxValue = 1 << 16;
            }
         }
         return maxValue;
   }

   private void updateBinSize() {
      if (binSize_ == 0) {
         binSize_ = getMaxValue() / 256;
      }
   }

   public void setDisplayRange(int min, int max) {
      acq_.setChannelDisplayRange(channelIndex_,
              min, max);
   }

   public final void drawDisplaySettings() {
      int min;
      int max;
      if (autostretch_) {
         int[] histogram = acq_.getChannelHistogram(channelIndex_);
         if (rejectOutliers_) {
            int totalPoints = acq_.getHyperImage().getWidth() * acq_.getHyperImage().getHeight();
            

            if (histogram != null) {
               HistogramUtils hu = new HistogramUtils(histogram, totalPoints, fractionToReject_);
               min = hu.getMinAfterRejectingOutliers();
               max = hu.getMaxAfterRejectingOutliers();
            } else {
               min = getMin();
               max = getMax();
            }
         } else {
            min = getMin(histogram);
            max = getMax(histogram);
         }
      } else {
         min = acq_.getChannelMin(channelIndex_);
         max = acq_.getChannelMax(channelIndex_);
      }

      hp_.setCursors(min / binSize_,
                     max / binSize_,
                     acq_.getChannelGamma(channelIndex_));
      minLabel.setText("min: " + getMin());
      maxLabel.setText("max: " + getMax());
      histMax_ = Integer.toString((int) (binSize_ * 256));
      hp_.repaint();
   }


   private GraphData makeGraphData(int [] rawHistogram) {
      GraphData graphData = new GraphData();
      if (rawHistogram == null) {
         return graphData;
      }

      updateBinSize();

      int[] histogram = new int[256]; // 256 bins
      int limit = Math.min((int) (rawHistogram.length / binSize_), 256);
      for (int i = 0; i < limit; i++) {
         histogram[i] = 0;
         for (int j = 0; j < binSize_; j++) {
            histogram[i] += rawHistogram[(int) (i * binSize_) + j];
         }
         if (logScale_) {
            histogram[i] = histogram[i] > 0 ? (int) (1000 * Math.log(histogram[i])) : 0;
         }
      }

      graphData.setData(histogram);
      return graphData;
   }


   private void setFullRange() {
      int maxValue = getMaxValue();
      turnOffAutostretch();
      setDisplayRange(0, maxValue);
   }

   private void setAutoRange() {
      int [] histogram = acq_.getChannelHistogram(channelIndex_);
      int min = 0;
      int max = 0;
      if (histogram != null) {
         for (int i = 0; i < histogram.length; ++i) {
            if (histogram[i] != 0 && min == 0) {
               min = i;
               max = min;
            }
            if (histogram[i] != 0) {
               max = i;
            }
         }
         setDisplayRange(min, max);
      }
   }

   private int getMin() {
      int[] histogram = acq_.getChannelHistogram(channelIndex_);
      return getMin(histogram);
   }

   private int getMin(int[] histogram) {
      if (histogram != null) {
         int min = 0;
         for (int i = 0; i < histogram.length; ++i) {
            if (histogram[i] != 0 && min == 0) {
               min = i;
            }
         }
         return min;
      } else {
         return 0;
      }
   }
   
   private int getMax() {
      int[] histogram = acq_.getChannelHistogram(channelIndex_);
      return getMax(histogram);
   }

   private int getMax(int[] histogram) {
      if (histogram != null) {
         int min = 0;
         int max = 0;
         for (int i = 0; i < histogram.length; ++i) {
            if (histogram[i] != 0 && min == 0) {
               min = i;
               max = min;
            }
            if (histogram[i] != 0) {
               max = i;
            }
         }
         return max;
      } else {
         return 0;
      }
   }


   public double getFractionToReject(){
      return fractionToReject_;
   }

   public void setFractionToReject(double v){
      double oldVal = fractionToReject_;
      fractionToReject_ = v;
      if (v != oldVal) {
         updateChannelSettings();
      }

   }

}
