/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HyperstackControls.java
 *
 * Created on Jul 15, 2010, 2:54:37 PM
 */

package org.micromanager.acquisition;

/**
 *
 * @author arthur
 */
public class HyperstackControls extends java.awt.Panel {

    /** Creates new form HyperstackControls */
    public HyperstackControls() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      metadataButton = new javax.swing.JButton();
      showFolderButton = new javax.swing.JButton();
      contrastButton = new javax.swing.JButton();
      saveButton = new javax.swing.JButton();

      setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      metadataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/micromanager/icons/application_view_list.png"))); // NOI18N
      metadataButton.setFocusable(false);
      metadataButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      metadataButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      add(metadataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

      showFolderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/micromanager/icons/folder.png"))); // NOI18N
      showFolderButton.setFocusable(false);
      showFolderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      showFolderButton.setMaximumSize(new java.awt.Dimension(28, 20));
      showFolderButton.setMinimumSize(new java.awt.Dimension(28, 20));
      showFolderButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      add(showFolderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

      contrastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/micromanager/icons/contrast.png"))); // NOI18N
      contrastButton.setFocusable(false);
      contrastButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      contrastButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      add(contrastButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

      saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/micromanager/icons/disk.png"))); // NOI18N
      saveButton.setFocusable(false);
      saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton contrastButton;
   private javax.swing.JButton metadataButton;
   private javax.swing.JButton saveButton;
   private javax.swing.JButton showFolderButton;
   // End of variables declaration//GEN-END:variables

}
