/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetadataViewer.java
 *
 * Created on Jul 16, 2010, 11:18:45 AM
 */
package org.micromanager.acquisition;

import ij.ImageListener;
import ij.ImagePlus;
import ij.ImageStack;
import ij.WindowManager;
import ij.gui.ImageWindow;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.util.Vector;
import javax.swing.table.AbstractTableModel;
import mmcorej.Metadata;
import mmcorej.StrMap;

/**
 *
 * @author arthur
 */
public class MetadataViewer extends javax.swing.JFrame
        implements ImageListener, AWTEventListener {

   private static MetadataViewer singletonViewer_ = null;
   private final MetadataTableModel model_;
   private ImageWindow currentWindow_;
   private final String [] columnNames_ = {"Property","Value"};
   
   /** Creates new form MetadataViewer */
   public MetadataViewer() {
      initComponents();
      model_ = new MetadataTableModel();

      ImagePlus.addImageListener(this);
      update(ij.IJ.getImage());
      metadataTable.setModel(model_);
      this.getToolkit().addAWTEventListener(this, AWTEvent.WINDOW_FOCUS_EVENT_MASK);
   }

   public static MetadataViewer showMetadataViewer() {
      if (singletonViewer_ == null) {
         singletonViewer_ = new MetadataViewer();
      }
      singletonViewer_.setVisible(true);
      return singletonViewer_;
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      metadataTableScrollPane = new javax.swing.JScrollPane();
      metadataTable = new javax.swing.JTable();

      setTitle("Metadata");

      metadataTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Property", "Value"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      metadataTable.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      metadataTable.setDoubleBuffered(true);
      metadataTableScrollPane.setViewportView(metadataTable);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(metadataTableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .add(metadataTableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   class MetadataTableModel extends AbstractTableModel {

      Vector<Vector<String>> data_;

      MetadataTableModel() {
         data_ = new Vector<Vector<String>>();
      }

      public int getRowCount() {
         return data_.size();
      }

      public void addRow(Vector<String> rowData) {
         data_.add(rowData);
      }

      public int getColumnCount() {
         return 2;
      }

      public Object getValueAt(int rowIndex, int columnIndex) {
         return data_.get(rowIndex).get(columnIndex);
      }

      public void clear() {
         data_.clear();
      }

      @Override
      public String getColumnName(int colIndex) {
         return columnNames_[colIndex];
      }

      public void setMetadata(Metadata md) {
         clear();
         if (md != null) {
            StrMap data = md.getFrameData();
            for (String key : md.getFrameKeys()) {
               Vector<String> rowData = new Vector<String>();
               rowData.add(key);
               rowData.add(data.get(key));
               addRow(rowData);
            }
         }
         fireTableDataChanged();
      }
   }

   public void update(ImagePlus imp) {
      if (this.isVisible()) {
         if (imp == null) {
            model_.setMetadata(null);
         } else {
            ImageStack stack = imp.getStack();
            if (stack instanceof AcquisitionVirtualStack) {
               AcquisitionVirtualStack vstack = (AcquisitionVirtualStack) imp.getStack();
               int slice = imp.getCurrentSlice();
               Metadata md = vstack.getTaggedImage(slice).md;
               model_.setMetadata(md);
            } else {
               model_.setMetadata(null);
            }
         }
      }
   }

   @Override
   public void setVisible(boolean visible) {
      super.setVisible(visible);
      if (visible)
         eventDispatched(null);
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTable metadataTable;
   private javax.swing.JScrollPane metadataTableScrollPane;
   // End of variables declaration//GEN-END:variables


   //Implements ImageListener
   public void imageOpened(ImagePlus imp) {
      update(imp);
   }

   //Implements ImageListener
   public void imageClosed(ImagePlus imp) {
      if (WindowManager.getCurrentWindow() == null) {
         update((ImagePlus) null);
      }
   }

   //Implements ImageListener
   public void imageUpdated(ImagePlus imp) {
      update(imp);
   }


   //Implements AWTEventListener
   public void eventDispatched(AWTEvent event) {
      ImageWindow currentWindow = WindowManager.getCurrentWindow();
      if (currentWindow_ != currentWindow) {
         ImagePlus imgp = currentWindow.getImagePlus();
         update(imgp);
      }
   }
}
