/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DetectorJDialog.java
 *
 * Created on Feb 11, 2011, 11:30:21 AM
 */

package org.micromanager.conf;

/**
 *
 * @author Karl Hoover
 */
public class DetectorJDialog extends javax.swing.JDialog {

    public boolean CancelRequest(){
        return cancelRequest_;
    }

    public void ProgressText( String t){
        detectionTextArea_.setText(t);
    }

    public String ProgressText(){
        return detectionTextArea_.getText();
    }

    private boolean cancelRequest_;
    /** Creates new form DetectorJDialog */
    public DetectorJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cancelRequest_ = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detectionTextArea_ = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cancelButton_.setText("Cancel");
        cancelButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton_ActionPerformed(evt);
            }
        });

        detectionTextArea_.setColumns(20);
        detectionTextArea_.setRows(5);
        jScrollPane1.setViewportView(detectionTextArea_);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(cancelButton_))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(cancelButton_)
                .addGap(24, 24, 24))
        );

        cancelButton_.getAccessibleContext().setAccessibleDescription("Cancel");

        getAccessibleContext().setAccessibleName("detectionTextArea");
        getAccessibleContext().setAccessibleDescription("detectionTextArea");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton_ActionPerformed
       System.out.print("cancelButton_ActionPerformed");
        cancelRequest_ = true;
    }//GEN-LAST:event_cancelButton_ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton_;
    private javax.swing.JTextArea detectionTextArea_;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
