/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.epfl.leb.autolase;

import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author pengo
 */
public class AutoLaseDialog extends javax.swing.JDialog implements DensityMonitor, LaserPowerMonitor {
    public static final int DENSITY_STEPS = 1000;

    AutoLase autoLase;
    
    AutoLaseOptionsDialog alg; 
    
    LaserConfig lc;
    
    Camera mmcoreCamera;

    
    /**
     * Creates new form AutoLaseDialog
     */
    public AutoLaseDialog(java.awt.Frame parent, boolean modal, AutoLase autoLase) {
        super(parent, modal);
        initComponents();
        
        this.autoLase = autoLase;
        mmcoreCamera = autoLase.getCamera();
        
        autoLase.addDensityMonitor(this);
        autoLase.addLaserPowerMonitor(this);
        
        jpbDensity.setMaximum(DENSITY_STEPS);
    }

    double maxDensity = 0, curDensity = 0;
    @Override
    public void densityChanged(double density) {
        curDensity = density;
        
        if (maxDensity < density)
            setMaxDensity(density);
        
        int v = (int)(density/maxDensity * DENSITY_STEPS);
        
        jpbDensity.setValue(v);
        jlCurrentDensity.setText(String.valueOf(density));
    }
    
    void setMaxDensity(double density) {
        maxDensity = density;
        jlMaxDensity.setText(String.valueOf(maxDensity));
   }

    double curLaserPower = 0;
    @Override
    public void laserPowerChanged(double newLaserPower) {
        jlCurLaserPower.setText(String.format("%7.2f", newLaserPower));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpbDensity = new javax.swing.JProgressBar();
        jlMaxDensity = new javax.swing.JLabel();
        jlMinDensity = new javax.swing.JLabel();
        jbPreBleach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfThreshold = new javax.swing.JTextField();
        jsThreshold = new javax.swing.JSlider();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jlCurrentDensity = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbImageMeanThreshold = new javax.swing.JButton();
        jcbDensityMap = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jtfMinGoodDensity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfMaxGoodDensity = new javax.swing.JTextField();
        jbOptions = new javax.swing.JButton();
        jtAutoLase = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jlCurLaserPower = new javax.swing.JLabel();
        jbLaserStartVal = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton_logFile = new javax.swing.JButton();
        jcbDensityProfile = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpbDensity.setOrientation(1);

        jlMaxDensity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlMaxDensity.setText("0");
        jlMaxDensity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMaxDensityMouseClicked(evt);
            }
        });

        jlMinDensity.setText("0");

        jbPreBleach.setText("Pre-bleach");
        jbPreBleach.setEnabled(false);
        jbPreBleach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreBleachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("AutoLase");

        jLabel2.setText("Automated single-molecule density control via laser");

        jLabel3.setText("Density");

        jLabel6.setText("Image threshold");

        jtfThreshold.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfThreshold.setText("500");
        jtfThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfThresholdActionPerformed(evt);
            }
        });

        jsThreshold.setMaximum(16384);
        jsThreshold.setValue(500);
        jsThreshold.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsThresholdStateChanged(evt);
            }
        });

        jToggleButton1.setText("Monitor");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Current density");

        jlCurrentDensity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlCurrentDensity.setText("0");

        jbImageMeanThreshold.setText("Auto");
        jbImageMeanThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImageMeanThresholdActionPerformed(evt);
            }
        });

        jcbDensityMap.setText("Show density map");
        jcbDensityMap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbDensityMapItemStateChanged(evt);
            }
        });

        jLabel9.setText("Good density from ");

        jtfMinGoodDensity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfMinGoodDensity.setText("100");
        jtfMinGoodDensity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinGoodDensityActionPerformed(evt);
            }
        });

        jLabel10.setText("to");

        jtfMaxGoodDensity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfMaxGoodDensity.setText("200");
        jtfMaxGoodDensity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaxGoodDensityActionPerformed(evt);
            }
        });

        jbOptions.setText("Laser Options");
        jbOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOptionsActionPerformed(evt);
            }
        });

        jtAutoLase.setForeground(new java.awt.Color(255, 0, 0));
        jtAutoLase.setText("AutoLase!");
        jtAutoLase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAutoLaseActionPerformed(evt);
            }
        });

        jLabel4.setText("Current laser power");

        jlCurLaserPower.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlCurLaserPower.setText("0");

        jbLaserStartVal.setText("Laser = Default");
        jbLaserStartVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLaserStartValActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Use TIFF...");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton_logFile.setText("Start log file");
        jButton_logFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logFileActionPerformed(evt);
            }
        });

        jcbDensityProfile.setText("Show density profile");
        jcbDensityProfile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbDensityProfileItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlMaxDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jSeparator2)
                                        .addGap(8, 8, 8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbPreBleach)
                                        .addGap(39, 39, 39)
                                        .addComponent(jtAutoLase)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jlCurLaserPower, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbLaserStartVal))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton_logFile)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jToggleButton2))
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)
                                .addComponent(jlMinDensity))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jlCurrentDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jtfThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbImageMeanThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jsThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfMinGoodDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfMaxGoodDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbDensityProfile)
                                            .addComponent(jcbDensityMap))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpbDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlMaxDensity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jlCurrentDensity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jtfThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbImageMeanThreshold))
                            .addComponent(jsThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfMinGoodDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jtfMaxGoodDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(jcbDensityMap))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jlMinDensity)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbDensityProfile)
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jlCurLaserPower)
                                    .addComponent(jbLaserStartVal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtAutoLase)
                                    .addComponent(jbPreBleach)
                                    .addComponent(jbOptions))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jToggleButton2)
                                    .addComponent(jButton_logFile)))))
                    .addComponent(jpbDensity, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfThresholdActionPerformed
        try {
            jsThreshold.setValue(Integer.valueOf(jtfThreshold.getText()));
        } catch(NumberFormatException ne) {
            JOptionPane.showMessageDialog(this, "Threshold must be between "+jsThreshold.getMinimum()+" and "+jsThreshold.getMaximum());
        }
    }//GEN-LAST:event_jtfThresholdActionPerformed

    private void jbPreBleachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreBleachActionPerformed
        // Put into pre-bleach mode
        
        // TODO turn off other components
        
        autoLase.preBleach();
    }//GEN-LAST:event_jbPreBleachActionPerformed

    private void jsThresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsThresholdStateChanged
        int threshold = jsThreshold.getValue();
        
        jtfThreshold.setText(
                String.valueOf(threshold));
        
        autoLase.setThreshold(threshold);
    }//GEN-LAST:event_jsThresholdStateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            autoLase.startDensityMonitor();
        } else {
            autoLase.pauseDensityMonitor();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    
    private void jlMaxDensityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMaxDensityMouseClicked
        setMaxDensity(2*curDensity);
    }//GEN-LAST:event_jlMaxDensityMouseClicked

    private void jcbDensityMapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbDensityMapItemStateChanged
        autoLase.showDensityMapMonitor(jcbDensityMap.isSelected());
    }//GEN-LAST:event_jcbDensityMapItemStateChanged

    private void jtfMaxGoodDensityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaxGoodDensityActionPerformed
        try {
            autoLase.setMaxGoodDensity(Float.valueOf(jtfMaxGoodDensity.getText()));
            jtfMaxGoodDensity.setForeground(Color.BLACK);
        } catch (NumberFormatException e) {
            jtfMaxGoodDensity.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jtfMaxGoodDensityActionPerformed

    private void jtfMinGoodDensityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinGoodDensityActionPerformed
        try {
            autoLase.setMinGoodDensity(Float.valueOf(jtfMinGoodDensity.getText()));
            jtfMinGoodDensity.setForeground(Color.BLACK);
        } catch (NumberFormatException e) {
            jtfMinGoodDensity.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jtfMinGoodDensityActionPerformed

    private void jbImageMeanThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImageMeanThresholdActionPerformed
        int threshold = autoLase.getAutoThreshold();
        autoLase.setThreshold(threshold);
        jtfThreshold.setText(String.valueOf(threshold));
    }//GEN-LAST:event_jbImageMeanThresholdActionPerformed

    private void jbOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOptionsActionPerformed
        // Open configuration dialog
        if (alg == null) {
            alg = new AutoLaseOptionsDialog(autoLase.config, null, true);
        }
        
        alg.setVisible(true);
    }//GEN-LAST:event_jbOptionsActionPerformed

    private void jtAutoLaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAutoLaseActionPerformed
        if (jtAutoLase.isSelected())
            autoLase.startLaserControl();
        else
            autoLase.pauseLaserControl();
    }//GEN-LAST:event_jtAutoLaseActionPerformed

    private void jbLaserStartValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLaserStartValActionPerformed
        autoLase.setLaserToStartPower();
    }//GEN-LAST:event_jbLaserStartValActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (jToggleButton2.isSelected()) {
            // Use TIFF
            JFileChooser jfc = new JFileChooser();
            int ret = jfc.showOpenDialog(this);
            if (ret == JFileChooser.APPROVE_OPTION) {
                try {
                    autoLase.setCamera(new TiffCamera(jfc.getSelectedFile()));
                    jToggleButton2.setText("Use Camera");
                } catch (Exception e) {
                    autoLase.log("Unable to set camera to read from "+jfc.getSelectedFile().getAbsolutePath());
                    jToggleButton2.setSelected(false);
                }
            }
        } else {
            // Reset to the saved camera
            autoLase.setCamera(mmcoreCamera);
            
            jToggleButton2.setText("Use TIFF...");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

   private void jButton_logFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logFileActionPerformed
      if (!autoLase.logFileIsStarted){
         autoLase.startLogFile();
         jButton_logFile.setText("Stop logging");
      } else {
         autoLase.stopLogFile();
         jButton_logFile.setText("Start log file");
      }
      
   }//GEN-LAST:event_jButton_logFileActionPerformed

   private void jcbDensityProfileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbDensityProfileItemStateChanged
        autoLase.showDensityProfileMonitor(jcbDensityProfile.isSelected());
   }//GEN-LAST:event_jcbDensityProfileItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton jbImageMeanThreshold;
    private javax.swing.JButton jbLaserStartVal;
    private javax.swing.JButton jbOptions;
    private javax.swing.JButton jbPreBleach;
    private javax.swing.JCheckBox jcbDensityMap;
    private javax.swing.JCheckBox jcbDensityProfile;
    private javax.swing.JLabel jlCurLaserPower;
    private javax.swing.JLabel jlCurrentDensity;
    private javax.swing.JLabel jlMaxDensity;
    private javax.swing.JLabel jlMinDensity;
    private javax.swing.JProgressBar jpbDensity;
    private javax.swing.JSlider jsThreshold;
    private javax.swing.JToggleButton jtAutoLase;
    private javax.swing.JTextField jtfMaxGoodDensity;
    private javax.swing.JTextField jtfMinGoodDensity;
    private javax.swing.JTextField jtfThreshold;
    // End of variables declaration//GEN-END:variables

   public void densityThreadStarted() {
      //DO NOTHING
   }

   public void densityThreadStopped() {
      //DO NOTHING
   }

   public void laserThreadStarted() {
      //DO NOTHING
   }

   public void laserThreadStopped() {
      //DO NOTHING
   }
}
