/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.micromanager.magellan.internal.gui;

import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import org.micromanager.magellan.internal.channels.ChannelGroupSettings;
import org.micromanager.magellan.internal.magellanacq.MagellanDataManager;
import org.micromanager.ndviewer.api.ControlsPanelInterface;

/**
 *
 * @author henrypinkard
 */
public class ExploreControlsPanel extends javax.swing.JPanel implements ControlsPanelInterface {

   private ChannelGroupSettings channels_; 
   private MagellanDataManager manager_;
   private ExploreZSliders zSliders_;

   /**
    * Creates new form ExploreChannelsPanel
    */
   public ExploreControlsPanel(MagellanDataManager manager, ChannelGroupSettings channels) {
      channels_ = channels;
      manager_ = manager;
      zSliders_ = new ExploreZSliders(manager);
      initComponents();


      //left justified editor
      JTextField tf = new JTextField();
      tf.setHorizontalAlignment(SwingConstants.LEFT);
      DefaultCellEditor ed = new DefaultCellEditor(tf);
      channelsTable_.getColumnModel().getColumn(2).setCellEditor(ed);
      //and renderer
      DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
      renderer.setHorizontalAlignment(SwingConstants.LEFT); // left justify
      channelsTable_.getColumnModel().getColumn(2).setCellRenderer(renderer);
      channelsTable_.getColumnModel().getColumn(0).setMaxWidth(30); //Acitve checkbox column
      if (channels_ == null) {
         jScrollPane2.setVisible(false);
         selectUseAllButton_.setVisible(false);
         syncExposuresButton_.setVisible(false);
      }
   }
   
   public void updateExploreZControls(Integer zIndex) {
      zSliders_.updateExploreZControls(zIndex);
   }

   @Override
   public void selected() {
      manager_.update();
   }
   
   @Override
   public void deselected() {
      manager_.update();
   }

   @Override
   public String getTitle() {
      return "Explore controls";
   }

   @Override
   public void close() {
      ((SimpleChannelTableModel) channelsTable_.getModel()).shutdown();
      manager_ = null;
      channelsTable_ = null;
      zSliders_.onDisplayClose();
      zSliders_ = null;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      zPanelPanel_ = new javax.swing.JPanel();
      zPanelPanel_.add(zSliders_);
      jPanel2 = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JPanel();
      acquireAtCurrentButton_ = new javax.swing.JButton();
      selectUseAllButton_ = new javax.swing.JButton();
      syncExposuresButton_ = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      channelsTable_ = new javax.swing.JTable();

      zPanelPanel_.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

      jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

      acquireAtCurrentButton_.setText("Acquire at current position");
      acquireAtCurrentButton_.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            acquireAtCurrentButton_ActionPerformed(evt);
         }
      });
      jPanel1.add(acquireAtCurrentButton_);

      selectUseAllButton_.setText("Select all");
      selectUseAllButton_.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            selectUseAllButton_ActionPerformed(evt);
         }
      });
      jPanel1.add(selectUseAllButton_);

      syncExposuresButton_.setText("Sync exposures");
      syncExposuresButton_.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            syncExposuresButton_ActionPerformed(evt);
         }
      });
      jPanel1.add(syncExposuresButton_);

      channelsTable_.setModel(new SimpleChannelTableModel(channels_,false));
      jScrollPane2.setViewportView(channelsTable_);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(zPanelPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(zPanelPanel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void syncExposuresButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncExposuresButton_ActionPerformed
      ((SimpleChannelTableModel) channelsTable_.getModel()).synchronizeExposures();
      ((SimpleChannelTableModel) channelsTable_.getModel()).fireTableDataChanged();
   }//GEN-LAST:event_syncExposuresButton_ActionPerformed

   private void selectUseAllButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUseAllButton_ActionPerformed
      ((SimpleChannelTableModel) channelsTable_.getModel()).selectAllChannels();
      ((SimpleChannelTableModel) channelsTable_.getModel()).fireTableDataChanged();
   }//GEN-LAST:event_selectUseAllButton_ActionPerformed

   private void acquireAtCurrentButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquireAtCurrentButton_ActionPerformed
      manager_.acquireTileAtCurrentPosition();
   }//GEN-LAST:event_acquireAtCurrentButton_ActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton acquireAtCurrentButton_;
   private javax.swing.JTable channelsTable_;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JButton selectUseAllButton_;
   private javax.swing.JButton syncExposuresButton_;
   private javax.swing.JPanel zPanelPanel_;
   // End of variables declaration//GEN-END:variables


}
