/**
 * ExampleFrame.java
 *
 *
 * This is merely a skeleton showing how to start writing a Micro-Manager
 * plugin. This specific example uses the NetBeans GUI builder. You can safely
 * take out those parts (and remove the .form file) and build your own
 * interface.
 *
 *
 * It should not be added to the Micro-Manager distribution (as it is quite
 * limited in functionality).
 *
 *
 * Nico Stuurman, copyright UCSF, 2012, 2015
 *
 * LICENSE: This file is distributed under the BSD license. License text is
 * included with the source distribution.
 *
 * This file is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.
 *
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES.
 */
package org.micromanager.example;

import mmcorej.CMMCore;

import java.text.NumberFormat;

import org.micromanager.Studio;
import org.micromanager.internal.utils.MMFrame;

/**
 *
 * @author nico
 */
public class ExampleFrame extends MMFrame {

   private final Studio gui_;
   private final CMMCore core_;

   private final NumberFormat nf_;
   
   private int counter_;
   private static final String COUNTER = "counter";

   /**
    * Constructor
    *
    * @param gui - Reference to MM script interface
    */
   public ExampleFrame(Studio gui) {
      gui_ = gui;
      core_ = gui_.getCMMCore();
      nf_ = NumberFormat.getInstance();
      
      counter_ = gui_.profile().getInt(this.getClass(), COUNTER, 0);

      initComponents();
      
      loadAndRestorePosition(100, 100);

   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   //@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextField5 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      OKButton_ = new javax.swing.JButton();

      setTitle("Example Plugin");
      setLocationByPlatform(true);
      setResizable(false);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosing(java.awt.event.WindowEvent evt) {
            onWindowClosing(evt);
         }
      });

      jLabel1.setText("This plugin does nothing");

      OKButton_.setText("OK");
      OKButton_.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            OKButton_ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(227, Short.MAX_VALUE)
            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(49, 49, 49)
                  .addComponent(jLabel1))
               .addGroup(layout.createSequentialGroup()
                  .addGap(77, 77, 77)
                  .addComponent(OKButton_)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(26, 26, 26)
            .addComponent(OKButton_)
            .addGap(42, 42, 42)
            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * When window closes, take the opportunity to clean up
    *
    * @param evt
    */
    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing

    }//GEN-LAST:event_onWindowClosing

   private void OKButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButton_ActionPerformed
      counter_++;
      gui_.profile().setInt(this.getClass(), COUNTER, counter_);
   }//GEN-LAST:event_OKButton_ActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton OKButton_;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JTextField jTextField5;
   // End of variables declaration//GEN-END:variables

}
