#!/bin/bash
#
# Install gphoto2 camera and i/o drivers in Micro-Manager directory 
#

#
# end result:
#
# Micro-Manager/libmmgr_dal_GPhoto: GPhoto device driver
#
# Micro-Manager/libgphoto2: shared libraries
#  libgphoto2.2.dylib
#  libgphoto2_port.0.dylib
#
# Micro-Manager/libgphoto2/libgphoto2: camera drivers
#  canon.so
#  ptp2.so
#  ...
#
# Micro-Manager/libgphoto2/libgphoto2_port: io drivers
#  serial.so
#  usb.so
#  ...
#
# for all shared libraries, camera and io drivers in Micro-Manager/libgphoto2, and for libmmgr_dal_GPhoto , the GPhoto driver itself:
#
# dynamic linkages to /opt/local/lib/libgphoto2.2.dylib have been changed to Micro-Manager/libgphoto2/libgphoto2.2.dylib
# dynamic linkages to /opt/local/lib/libgphoto2_port.0.dylib have been changed to Micro-Manager/libgphoto2/libgphoto2_port.0.dylib
#
# These dynamic linkages can be verified with otool -L :
#
# SimpleCam koen$ otool -L .libs/libmmgr_dal_GPhoto.so 
# .libs/libmmgr_dal_GPhoto.so:
#    /opt/local/lib/libgphoto2.2.dylib (compatibility version 7.0.0, current version 7.0.0)
#    /opt/local/lib/libgphoto2_port.0.dylib (compatibility version 9.0.0, current version 9.0.0)
#    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.6)
#    /usr/lib/libltdl.3.dylib (compatibility version 5.0.0, current version 5.4.0)
#    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
#    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
#
# SimpleCam koen$ otool -L /Applications/Micro-Manager1.4/libmmgr_dal_GPhoto 
# /Applications/Micro-Manager1.4/libmmgr_dal_GPhoto:
#    @loader_path/libgphoto2/libgphoto2.2.dylib (compatibility version 7.0.0, current version 7.0.0)
#    @loader_path/libgphoto2/libgphoto2_port.0.dylib (compatibility version 9.0.0, current version 9.0.0)
#    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.6)
#    /usr/lib/libltdl.3.dylib (compatibility version 5.0.0, current version 5.4.0)
#    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
#    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
#

#
# Assume we are in DeviceAdapters/SimpleCam and compiled driver is in .libs/libmmgr_dal_GPhoto.so
#
DESTDIR=/Applications/Micro-Manager1.4
LIBGPHOTO2LIBDIR=/usr/local/lib
LIBGPHOTO2=libgphoto2.dylib
LIBGPHOTO2PORT=libgphoto2_port.dylib

GPHOTO2_VERSION=`pkg-config libgphoto2 --variable=VERSION`
GPHOTO2_PORT_VERSION=`pkg-config libgphoto2_port --variable=VERSION`


cp ../.libs/libmmgr_dal_GPhoto $DESTDIR/libmmgr_dal_GPhoto

cd $DESTDIR

rm -rf libgphoto2

mkdir libgphoto2

cp $LIBGPHOTO2LIBDIR/$LIBGPHOTO2 libgphoto2/
install_name_tool -id @loader_path/libgphoto2/$LIBGPHOTO2 libgphoto2/$LIBGPHOTO2

# Change dynamic linkage in libgphoto2.2.dylib from /opt/local/lib/libgphoto2_port.0.dylib to Micro-Manager/libgphoto2/libgphoto2_port.0.dylib
install_name_tool -change $LIBGPHOTO2LIBDIR/$LIBGPHOTO2PORT @loader_path/$LIBGPHOTO2PORT libgphoto2/$LIBGPHOTO2

cp $LIBGPHOTO2LIBDIR/$LIBGPHOTO2PORT libgphoto2/
install_name_tool -id @loader_path/libgphoto2/$LIBGPHOTO2 libgphoto2/$LIBGPHOTO2

# Copy camera drivers
mkdir libgphoto2/libgphoto2
cp $LIBGPHOTO2LIBDIR/libgphoto2/$GPHOTO2_VERSION/*.so libgphoto2/libgphoto2/

# Copy io drivers
mkdir libgphoto2/libgphoto2_port
cp $LIBGPHOTO2LIBDIR/libgphoto2_port/$GPHOTO2_PORT_VERSION/*.so libgphoto2/libgphoto2_port/

# Change all dynamic linkages in Micro-Manager/libgphoto2/libgphoto2 and Micro-Manager/libgphoto2/libgphoto2_port
for SO in libgphoto2/libgphoto2/*.so libgphoto2/libgphoto2_port/*.so 
do
   install_name_tool -change $LIBGPHOTO2LIBDIR/$LIBGPHOTO2 @loader_path/../$LIBGPHOTO2 $SO
   install_name_tool -change $LIBGPHOTO2LIBDIR/$LIBGPHOTO2PORT @loader_path/../$LIBGPHOTO2PORT $SO
done

# Change dynamic linkages in Micro-Manager/libmmgr_dal_GPhoto 
install_name_tool -change $LIBGPHOTO2LIBDIR/$LIBGPHOTO2 @loader_path/libgphoto2/$LIBGPHOTO2 libmmgr_dal_GPhoto
install_name_tool -change $LIBGPHOTO2LIBDIR/$LIBGPHOTO2PORT @loader_path/libgphoto2/$LIBGPHOTO2PORT libmmgr_dal_GPhoto

# Add killptpcamera app
osacompile -e 'tell application "PTPCamera" to quit' -o libgphoto2/KillPtpCamera.app

#not truncated
