#!/bin/bash
#
# Configure and compile libgphoto2
#
export LIBUSB_LIBS="/opt/local/lib/libusb.a /opt/local/lib/libusb-1.0.a -framework IOKit -framework CoreFoundation "  
export LIBUSB_CFLAGS=-I/opt/local/include

rm -rf builddir
mkdir builddir
cd builddir

../libgphoto2-2.4.11/configure --enable-static --disable-nls --without-libexif --with-libiconv-prefix=/usr --prefix=/opt/local --with-drivers=adc65,agfa_cl20,aox,barbie,canon,casio_qv,clicksmart310,digigr8,digita,dimera3500,directory,enigma13,fuji,gsmart300,hp215,iclick,jamcam,jd11,kodak_dc120,kodak_dc210,kodak_dc240,kodak_dc3200,kodak_ez200,konica,konica_qm150,largan,lg_gsm,mars,dimagev,mustek,panasonic_coolshot,panasonic_l859,panasonic_dc1000,panasonic_dc1580,pccam300,pccam600,polaroid_pdc320,polaroid_pdc640,polaroid_pdc700,ptp2,ricoh,ricoh_g3,samsung,sierra,sipix_blink2,sipix_web2,smal,sonix,sony_dscf1,sony_dscf55,soundvision,spca50x,sq905,stv0674,stv0680,sx330z,toshiba_pdrm11
make

#not truncated
