#ifndef _VERSION_H_
#define _VERSION_H_

#define PVCAM_ADAPTER_VERSION_MAJOR    1
#define PVCAM_ADAPTER_VERSION_MINOR    0
#define PVCAM_ADAPTER_VERSION_BUILD    2
#define PVCAM_ADAPTER_VERSION_REVISION 0

#endif // _PVROI_H_